.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ryth-status 1  "status " 
.SH NAME
ryth\-status \- Current wifi status (state, signal, powered, etc.)
.SH SYNOPSIS
\fBstatus\fR [\fB\-\-watch\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Current wifi status (state, signal, powered, etc.)
.SH OPTIONS
.TP
\fB\-\-watch\fR
Stream updates on change
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
