.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ryth-power 1  "power " 
.SH NAME
ryth\-power \- Toggle wifi power
.SH SYNOPSIS
\fBpower\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISTATE\fR> 
.SH DESCRIPTION
Toggle wifi power
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISTATE\fR>

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
on
.IP \(bu 2
off
.RE
