.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ryth 1  "ryth " 
.SH NAME
ryth \- Scriptable iwd interface
.SH SYNOPSIS
\fBryth\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Scriptable iwd interface
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
ryth\-status(1)
Current wifi status (state, signal, powered, etc.)
.TP
ryth\-list(1)
List discovered networks (cached)
.TP
ryth\-scan(1)
Trigger a scan and return updated network list
.TP
ryth\-connect(1)
Connect to a network by SSID
.TP
ryth\-disconnect(1)
Disconnect from the current network
.TP
ryth\-autoconnect(1)
Toggle autoconnect for a known network
.TP
ryth\-forget(1)
Forget a known network
.TP
ryth\-known(1)
List known networks
.TP
ryth\-power(1)
Toggle wifi power
.TP
ryth\-help(1)
Print this message or the help of the given subcommand(s)
