.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ryth-disconnect 1  "disconnect " 
.SH NAME
ryth\-disconnect \- Disconnect from the current network
.SH SYNOPSIS
\fBdisconnect\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Disconnect from the current network
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
