.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ryth-connect 1  "connect " 
.SH NAME
ryth\-connect \- Connect to a network by SSID
.SH SYNOPSIS
\fBconnect\fR [\fB\-\-password\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISSID\fR> 
.SH DESCRIPTION
Connect to a network by SSID
.SH OPTIONS
.TP
\fB\-\-password\fR \fI<PASSWORD>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISSID\fR>

